// <auto-generated />
namespace SoBesedkaDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class repeatingdays_not_virtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repeatingdays_not_virtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201807011527186_repeatingdays_not_virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
